### ISSUE TITLE
Xcode freezes when I set the class of the label to FittableFontLabel

### ISSUE THREAD

**Issue by Sweeper777** [tbaranes/FittableFontLabel#11]
After installing the pod, I dragged a UILabel into a view controller's view. In the identity inspector, I typed "FittableFontLabel" in the "Class" textfield. Then Xcode freezes. I can do nothing but to force quit. I tried multiple times and the same thing happens: as soon as I typed "FittableFontLabel", Xcode just freezes!

I'm using Xcode 7.3.1 and CocoaPods 1.0.0.

Any ideas why?

**Comment by tbaranes** [comment]
I can't reproduce it using the demo project, do you? I'm using it in my own project, I never get this issue.
Right now, I have no idea why, is there anything special in your xib / storyboard ? Can you add some breakpoints in `FittableFontLabel` to see what's going wrong?

**Comment by tbaranes** [comment]
@Sweeper777  Just pushed a branch implementing the binary search algorithm (#17). That should be improved the `FittableFontLabel` performance, can you give a try?

**Comment by Sweeper777** [comment]
I tried it and it didn't freeze Xcode this time. Thanks for the fix!

**Comment by tbaranes** [comment]
Awesome! 🎉 
I will merge it and push a new release on monday (waiting to see if it's fix #14 too).
