### ISSUE TITLE
fontSizeThatFits() does not work when text is ""!

### ISSUE THREAD

**Issue by Sweeper777** [tbaranes/FittableFontLabel#15]
I just added a label to the storyboard, set up the constraints so that its bounds fills the whole screen. Then, in `viewDidLayoutSubviews`, I did this:

```
    // note that the label's text is not empty string here
    print(label.fontSizeThatFits(text: "00:00", maxFontSize: 500))
    print(label.fontSizeThatFits(text: "00:00:00", maxFontSize: 500))
```

And the values printed seems good. The first is larger than the second.

But if I do this:

```
    label.text = ""
    print(label.fontSizeThatFits(text: "00:00", maxFontSize: 500))
    print(label.fontSizeThatFits(text: "00:00:00", maxFontSize: 500))
```

It prints 17 and 17!

After looking into the source code, I think there is something wrong with the `currentAttributedStringAttributes()` method. But I'm quite inexperienced in dealing with `NSAttributedString`s so I can't figure out what is wrong.

Can you fix this?

**Comment by tbaranes** [comment]
Interesting. What size are you expecting for an empty string? Should it be 0? The max value available? The last font size used?

**Comment by Sweeper777** [comment]
I'm using `fontSizeThatFits`. It should return an appropriate font size for the text passed in regardless of the text of the label. In this case, I want to know the appropriate font size for "00:00" and "00:00:00".

**Comment by tbaranes** [comment]
Oh my bad, I misread your issue. I will take a look into this next week.
If you find a fix for this, don't hesitate to send a PR 👍

**Comment by tbaranes** [comment]
@Sweeper777 Can you try #16 and tell me if the fix works for you? I added some unit tests for `fontSizeThatFits`, it should be working as expected.
