### ISSUE TITLE
Binary search using 0.5 iterator and Swift compatibility

### ISSUE THREAD

**Issue by amarcadet** [tbaranes/FittableFontLabel#19]
What do you think about using `0.5` delta for each iteration during the binary search? (See example [https://github.com/ShingoFukuyama/UILabel-FontSizeToFit](https://github.com/ShingoFukuyama/UILabel-FontSizeToFit/blob/2bc76f3dcc23841040efbd56ee05070fe51ccfee/Swift/UILabel_FontSizeToFit/UILabel%2BFontSizeToFit.swift#L14))

I'm facing a use case where the font is considered `.Fit` 0.5pt too soon, maybe because the next iteration is considered `.TooSmall` and thus my text is truncated.

Also I can't move to Swift 3.x right now, what do you think about creating a separator release cycle for 2.3 support?
Per semver, breaking changes should bump major version number (see [changelog](https://github.com/tbaranes/FittableFontLabel/blob/master/CHANGELOG.md#140-11-09-2016)).

Thanks!

**Comment by tbaranes** [comment]
Starting with the v1.3.0, there's no notion of `diminishRate`. How do you want to add this? 

For the semserver, you are right, I should have follow them. Promise, I will be more careful starting with the next release!  
I don't plan to add any swift 2.3 support, but if you want to send a PR, I will definitely review it, I'm ok to have a release supporting it.

**Comment by amarcadet** [comment]
I don't know what's the best way to do it (hardcoded or parameter), either way I'm facing an issue where the required font is `58.5` and the binary search stops at `59`.

If you don't plan to support 2.3, then I must find another way or stick with 1.3.
Any PR would be done on a 3.x codebase and I won't be able to test and use it for now.
So I think I'm going to create my own fork, and come back here when I'll move to Swift 3.x.
