### ISSUE TITLE
Memory leak while using Savoye LET font

### ISSUE THREAD

**Issue by dzpt** [tbaranes/FittableFontLabel#2]
Hey, i've found one new issue here.
If i use Savoye LET (one of the default fonts) , the memory leak happens.

**Comment by tbaranes** [comment]
I will try to reproduce it next week (will be hard this week...). Till then, if you find the issue, could you make a PR? It would be awesome 🎉

**Comment by dzpt** [comment]
Yep. i will. Testing for more issue and i will make a PR.

**Comment by tbaranes** [comment]
I try to reproduce it using the example project, but can't found any leaks. Are you sure that the leak is not from your project?
