### ISSUE TITLE
Why does the text not fit in the label in this case?

### ISSUE THREAD

**Issue by Sweeper777** [tbaranes/FittableFontLabel#22]
I have a label that says "5" like this:

<img width="492" alt="2017-09-09 10 09 53" src="https://user-images.githubusercontent.com/13585047/30246753-dc3f2c8e-95fa-11e7-8915-c9fc20c99b1d.png">
<img width="253" alt="2017-09-10 7 35 38" src="https://user-images.githubusercontent.com/13585047/30246754-dea042f6-95fa-11e7-8a2b-b00c4f4c9aae.png">

At runtime, it shows up like this:

<img width="265" alt="2017-09-09 10 09 20" src="https://user-images.githubusercontent.com/13585047/30246764-06399a92-95fb-11e7-882b-6d8f19558243.png">

As you can see, the font size is too big. I cannot figure out why this is. I've set the "lines" property to 0 so it should fit both the width and height. I have also selected "Word Wrap" like you've said in README.

**Comment by tbaranes** [comment]
Right now, I can't tell. Did you check the demo app and compare both setup?

**Comment by Sweeper777** [comment]
Somehow, when I embed the labels in a stack view, the problem is gone...
