### ISSUE TITLE
Swift 4 / XCode 9.1 support

### ISSUE THREAD

**Issue by AncAinu** [tbaranes/FittableFontLabel#30]
![image](https://user-images.githubusercontent.com/1257961/32618424-9b423d3a-c56f-11e7-8cd9-3031cca21293.png)

**Comment by tbaranes** [comment]
I have an issue with cocoa pods, didn’t take the time to look into this yet, for an unknown reason, Cocoapods can’t compile the project, so the release process is failing. Since the last release support Xcode 9.1, you can manually target it (or use Carthage)

**Comment by tbaranes** [comment]
Finally understood what was happening, just released 2.0.0 on CocoaPods and Github, it includes support for Xcode 9 and Swift 4. Sorry for the inconvenience!
