### ISSUE TITLE
cannot compile in swift 4 project

### ISSUE THREAD

**Issue by nets-rac** [tbaranes/FittableFontLabel#32]
I added the pod to my workspace but then I get compile errors in UILabelExtension:

Cannot assign value of type '[NSAttributedStringKey : Any]' to type '[String : Any]'
Cannot subscript a value of type '[String : Any]' with an index of type 'NSAttributedStringKey'
Cannot convert value of type '[String : Any]' to expected argument type '[NSAttributedStringKey : Any]?'

**Comment by tbaranes** [comment]
Are you using the last version (2.0.0)? If yes, it should be supporting Swift 4.

**Comment by nets-rac** [comment]
Ok...I just added 
pod 'FittableFontLabel'

to my Podfile as it was described in the readme. But this did not install the latest (2.0) version.

now it works.
