### ISSUE TITLE
Error in FittableFontLabel.swift

### ISSUE THREAD

**Issue by Jovisx** [tbaranes/FittableFontLabel#35]
Change This:

open override func drawText(in rect: CGRect) {
        let insets = UIEdgeInsets(top: topInset, left: leftInset, bottom: bottomInset, right: rightInset)
        super.drawText(in: rect.inset(by: insets))

With This: (swift 4.2)

open override func drawText(in rect: CGRect) {
        let insets = UIEdgeInsets(top: topInset, left: leftInset, bottom: bottomInset, right: rightInset)
        super.drawText(in: UIEdgeInsetsInsetRect(rect, insets))
    }

}

**Comment by tbaranes** [comment]
Thanks for the report! Do you mind to open a PR?

**Comment by Jovisx** [comment]
I do not think to create a PR, open it for me and i will close the issues.
Thanks for everything ;)
