### ISSUE TITLE
SPM not working

### ISSUE THREAD

**Issue by Minimistro32** [tbaranes/FittableFontLabel#37]
After adding FittableFontLabel as a package with Swift Package Manager this error comes up:

"the manifest is missing a Swift tools version specification; consider prepending to the manifest '// swift-tools-version:5.5.0' to specify the current Swift toolchain version as the lowest Swift version supported by the project; if such a specification already exists, consider moving it to the top of the manifest, or prepending it with '//' to help Swift Package Manager find it"

**Comment by tbaranes** [comment]
You are right, this library hasn't been updated for latest SPM usage. Do you mind opening a PR fixing it?

**Comment by Minimistro32** [comment]
I don't know how at the moment, otherwise I definitely would. If I find the time before school starts up again I can try to figure it out and make a PR.
